### ISSUE TITLE
get version and manual in markdown?

### ISSUE THREAD

**Issue by GHolk** [kapouer/marked-man#10]
feeling give option in command line is troublesome. 
`marked-man --manual=mymanual --version=2 myman.md >myman.7`

have any idea about embed these two variable in markdown?
like `<!--MARKED-MAN VERSION=13 MANUAL=mymanual -->`
at very first line?

**Comment by kapouer** [comment]
The idea was to put that in the main title (at least for the version).

**Comment by kapouer** [comment]
I implemented another idea:
- `manual` is unset, so it defaults to the section number, which is specified by ronn format
- `version` (== `manVersion`) defaults to the version found in package.json of the module containing the markdown file being processed

This means `marked-man myman.md > myman.7` will just work if done in a js module.
