### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Valen-H** [kapouer/marked-man#21]
Using `--version` as shown in the example (in README) does not work and instead it gives this:

```
C:\Users\CodeDragon\Desktop\workspace\Node\dirstamp>marked-man --version v1.1.1 README.md
0.6.2
```

It just prints `0.6.2`, when i remove that flag, it works.

**Comment by Valen-H** [comment]
`marked` takes a `--version` flag as well, collision perhaps?

**Comment by kapouer** [comment]
Fixed in https://github.com/kapouer/marked-man/commit/7bd33606cffce6be75e1cba0cecc7b4236c9e7d5
