### ISSUE TITLE
Remove deprecated message

### ISSUE THREAD

**Issue by alinex** [kapouer/marked-man#24]
Since some days I got the following message every time I am using marked-man:

marked(): sanitize and sanitizer parameters are deprecated since version 0.7.0, should not be used and will be removed in the future. Read more here: https://marked.js.org/#/USING_ADVANCED.md#options

This is set within lib/marked-man.js line 457. Is it really needed then you should fix like described or disable this option.

**Comment by kapouer** [comment]
Fixed in 596eed292071fbd879ab93e7e99f9960a072a3ba
