### ISSUE TITLE
How to underline?

### ISSUE THREAD

**Issue by Sequoia** [kapouer/marked-man#3]
It seems it's a convention to underline switch argument:
![screenshot 2015-04-15 13 42 33](https://cloud.githubusercontent.com/assets/317498/7165366/4e4637d6-e375-11e4-9bc7-cc926720742e.png)

How do to this with marked-man?

**Comment by kapouer** [comment]
There is currently no obvious way of doing that.
I suppose marked-man should have its own markdown dialect to support things like that.

**Comment by kapouer** [comment]
oh wait, unless `_test_` works ?

**Comment by mklement0** [comment]
Yes, both `_test_` and `*test*` produce underlined output when viewed with `man`.

However, while you can craft such a syntax line to look nice with `man`, it won't look good in HTML, unfortunately, and, yes, short of introducing a new Markdown dialect, I don't see a solution to this problem.

**Comment by Sequoia** [comment]
thx
