### ISSUE TITLE
Wrong encoding and CRLF on Windows

### ISSUE THREAD

**Issue by fengshuo2004** [kapouer/marked-man#30]
### Bug

*marked-man* outputs `roff` files encoded in **UTF-16 Little Endian** w/ **CRLF** newline chars when ran under Windows.
Those files cannot be interpreted correctly by `/usr/bin/man` in Linux.
i.e. the correct encoding (UTF-8) and newline (LF) should be enforced on Windows.

### Reproduce

1. Install on Windows 10 `npm install -g marked-man`
2. Convert a markdown file
3. View the output on a Linux system (or WSL) `man ./mycommand.1`
4. See garbled output

Many thanks,
David

**Comment by kapouer** [comment]
It seems the problem comes from marked and not from marked-man, since marked is the one writing to a file.
However marked-man is compatible with an old version of marked and i didn't find the time to upgrade it.

**Comment by fengshuo2004** [comment]
> Is this still the case with marked-man 1.2 ?

I just updated to 1.2.4 and this package broke in a different, bizarre way...
Trying to run marked-man from powershell just errors out:

```
fengshuo > marked-man
&: D:\scoop\apps\nodejs\current\bin\marked-man.ps1:24
Line |
  24 |      & "/usr/bin/node$exe"  "$basedir/node_modules/marked-man/bin/mark …
     |        ~~~~~~~~~~~~~~~~~~~
     | The term '/usr/bin/node.exe' is not recognized as a name of a cmdlet, function, script file,
     | or executable program. Check the spelling of the name, or if a path was included, verify
     | that the path is correct and try again.
```

I think I've found the solution though, refer to this issue https://github.com/npm/npm/issues/1900
You need to change the first line in bin/marked-man.js from `#!/usr/bin/node` to `#!/usr/bin/env node` as it seems.

**Comment by kapouer** [comment]
Version 1.2.5 should address that last issue.

**Comment by fengshuo2004** [comment]
Confirm fixed. Manpages generated under Windows now has correct encoding/newline for viewing under Linux. Thank you 👍
