### ISSUE TITLE
Add compression support

### ISSUE THREAD

**Issue by piranna** [kapouer/marked-man#34]
Add option to generate gunzip compressed file with `.gz` extension.

**Comment by kapouer** [comment]
It is as simple as `marked-man doc.md | gzip > doc.1.gz`
Closing

**Comment by piranna** [comment]
ok, but being a standard format, I would add one option for that, specially since there's built-in support for gzip in node.js and there's no need to add external libraries...

**Comment by kapouer** [comment]
marked-man is here to do one job, and I barely find time to maintain it, let alone adding extra features that are obtainable easily.
