### ISSUE TITLE
graves inside a second-level heading render incorrectly

### ISSUE THREAD

**Issue by steveklabnik** [kapouer/marked-man#4]
Put this in a file named `test.md`:

```text
test
====

## this title `will render` strangely

This is the body text.
```

Then run this:

```bash
$ marked-man test.md > test.1
$ man ./test.1 
```

On my system, I get this:

![2015-07-17-195339_469x66_scrot](https://cloud.githubusercontent.com/assets/27786/8759223/7d5cdb06-2cbd-11e5-9a8d-6222fba94f11.png)

note that `strangely` is missing the highlight.

```troff
.SH this title \fBwill render\fR strangely
```

this is the text output, but I'm kind bad at `troff`, so I _think_ that `\fR` ends the formatting, but this is impossible to google, so hopefully you know :)

One solution is to just pitch anything in graves in a title: they're not being shown any differently anyway.

**Comment by steveklabnik** [comment]
Oh, this is affecting `npm`: https://github.com/npm/npm/issues/8984#issuecomment-122445431

**Comment by steveklabnik** [comment]
Ah ha!

`\fx` names a font `x`. So, here, `\fB` switches to bold, and `\fR` switches to 'roman'. `\fP` switches to 'previous`, and so I would recommend making this example render

```troff
.SH this title \fBwill render\fP strangely
```

which, on my machine, displays correctly, at least. Of course, `.SH` is already bold, it seems, so just not even showing anything differently might work. Another option:

```troff
.SH this title \fIwill render\fP strangely
```

This renders like this: 
![2015-07-17-200522_292x46_scrot](https://cloud.githubusercontent.com/assets/27786/8759300/3077238a-2cbf-11e5-810d-c1a8a6437d52.png)

**Comment by steveklabnik** [comment]
Actually https://www.gnu.org/software/groff/manual/html_node/Font-Families.html

>  Note that \FP doesn’t work; it selects font family ‘P’ instead. 

So the right thing is

>  If no argument is given, switch back to the previous font family.

**Comment by kapouer** [comment]
Thank you ! i've added a test case - and now i'm fixing the tests, comparing man output without formatting is too relaxed and doesn't test this issue.

**Comment by steveklabnik** [comment]
:confetti_ball: Thanks so much!
